import{a as w,i as p,S as P}from"./assets/vendor-eded45c0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const a of t)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(t){const a={};return t.integrity&&(a.integrity=t.integrity),t.referrerPolicy&&(a.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?a.credentials="include":t.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(t){if(t.ep)return;t.ep=!0;const a=o(t);fetch(t.href,a)}})();const x=document.querySelector(".loader"),q=document.querySelector(".loader2");function c(){x.classList.toggle("visually-hidden")}function d(){q.classList.toggle("visually-hidden")}async function m(s,e){const o="43682309-decfbd59f0a24849675c6bf75";e.currentPage===1?c():d();const r=await w.get("https://pixabay.com/api/",{params:{key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e.currentPage}});return e.currentPage+=1,r}function y(s){return s.map(({webformatURL:e,tags:o,largeImageURL:r,likes:t,views:a,comments:i,downloads:S})=>`<li class='card'>
        <a class="gallery-link" href="${r}"><img class='image' src='${e}' alt='${o}'></a>
        <div class='description'>
        <div class='title-text'><h4 class='title'>Likes</h4><p class='text'>${t}</p></div>
        <div class='title-text'><h4 class='title'>Views</h4><p class='text'>${a}</p></div>
        <div class='title-text'><h4 class='title'>Comments</h4><p class='text'>${i}</p></div>
        <div class='title-text'><h4 class='title'>Downloads</h4><p class='text'>${S}</p></div>
        </div>
        </li>`).join("")}const v=document.querySelector(".form"),u=document.querySelector(".searchInput"),n=document.querySelector(".list"),l=document.querySelector(".submitBtn"),h=document.querySelector(".loadMore"),g={currentPage:1};l.disabled=!0;function M(s,e){localStorage.setItem(s,e)}function C(s){const e=localStorage.getItem(s);return e||null}u.addEventListener("input",()=>{u.value.trim()!==""?l.disabled=!1:l.disabled=!0});v.addEventListener("submit",$);h.addEventListener("click",E);async function $(s){s.preventDefault();const e=u.value.trim();if(g.currentPage=1,e!==""){n.innerHTML="",L(),M("searchInputValue",e);try{const o=await m(e,g);if(o.data.hits.length===0)c(),f("Sorry, there are no images matching your search query. Please try again!");else{c(),n.insertAdjacentHTML("beforeend",y(o.data.hits)),I.refresh();const r=Math.ceil(o.data.totalHits/o.config.params.per_page);b(o,r)}v.reset(),l.disabled=!0}catch(o){c(),f(`${o}`)}}}async function E(){L();const s=C("searchInputValue");try{const e=await m(s,g),o=Math.ceil(e.data.totalHits/e.config.params.per_page);d(),n.insertAdjacentHTML("beforeend",y(e.data.hits)),I.refresh(),T(),b(e,o)}catch(e){d(),f(`${e}`)}}function T(){const e=n.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function f(s){p.error({message:s,position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",timeout:3e3})}function k(){p.warning({position:"topRight",backgroundColor:"#00A36C",message:"We're sorry, but you've reached the end of search results."})}function A(){h.classList.remove("visually-hidden")}function L(){h.classList.add("visually-hidden")}function b(s,e){const o=setInterval(()=>{if([...n.querySelectorAll("img")].every(a=>a.complete)){if(clearInterval(o),s.config.params.page>=e)return k();A()}},50)}const I=new P(".list a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
