import{a as S,i as h,S as w}from"./assets/vendor-eded45c0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const a of s)if(a.type==="childList")for(const i of a.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function o(s){const a={};return s.integrity&&(a.integrity=s.integrity),s.referrerPolicy&&(a.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?a.credentials="include":s.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function r(s){if(s.ep)return;s.ep=!0;const a=o(s);fetch(s.href,a)}})();const P=document.querySelector(".loader"),q=document.querySelector(".loader2");function x(){P.classList.toggle("visually-hidden")}function M(){q.classList.toggle("visually-hidden")}async function m(t,e){const o="43682309-decfbd59f0a24849675c6bf75";e.currentPage===1?x():M();const r=await S.get("https://pixabay.com/api/",{params:{key:o,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e.currentPage}});return e.currentPage+=1,r}function p(t){return t.map(({webformatURL:e,tags:o,largeImageURL:r,likes:s,views:a,comments:i,downloads:I})=>`<li class='card'>
        <a class="gallery-link" href="${r}"><img class='image' src='${e}' alt='${o}'></a>
        <div class='description'>
        <div class='title-text'><h4 class='title'>Likes</h4><p class='text'>${s}</p></div>
        <div class='title-text'><h4 class='title'>Views</h4><p class='text'>${a}</p></div>
        <div class='title-text'><h4 class='title'>Comments</h4><p class='text'>${i}</p></div>
        <div class='title-text'><h4 class='title'>Downloads</h4><p class='text'>${I}</p></div>
        </div>
        </li>`).join("")}const y=document.querySelector(".form"),d=document.querySelector(".searchInput"),n=document.querySelector(".list"),c=document.querySelector(".submitBtn"),g=document.querySelector(".loadMore"),u={currentPage:1};c.disabled=!0;function $(t,e){localStorage.setItem(t,e)}function C(t){const e=localStorage.getItem(t);return e||null}d.addEventListener("input",()=>{d.value.trim()!==""?c.disabled=!1:c.disabled=!0});y.addEventListener("submit",E);g.addEventListener("click",T);async function E(t){t.preventDefault();const e=d.value.trim();if(u.currentPage=1,e!==""){n.innerHTML="",v(),$("searchInputValue",e);try{l(!0);const o=await m(e,u);if(o.data.hits.length===0)f("Sorry, there are no images matching your search query. Please try again!");else{n.insertAdjacentHTML("beforeend",p(o.data.hits)),b.refresh();const r=Math.ceil(o.data.totalHits/o.config.params.per_page);L(o,r)}y.reset(),c.disabled=!0}catch(o){f(`${o}`)}finally{l(!1)}}}async function T(){v();const t=C("searchInputValue");try{l(!0);const e=await m(t,u),o=Math.ceil(e.data.totalHits/e.config.params.per_page);n.insertAdjacentHTML("beforeend",p(e.data.hits)),b.refresh(),k(),L(e,o)}catch(e){f(`${e}`)}finally{l(!1)}}function k(){const e=n.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function f(t){h.error({message:t,position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",timeout:3e3})}function A(){h.warning({position:"topRight",backgroundColor:"#00A36C",message:"We're sorry, but you've reached the end of search results."})}function O(){g.classList.remove("visually-hidden")}function v(){g.classList.add("visually-hidden")}function L(t,e){const o=setInterval(()=>{[...n.querySelectorAll("img")].every(a=>a.complete)&&(clearInterval(o),t.config.params.page>=e?A():O())},50)}function l(t){const e=document.querySelector(".loader");t?e.classList.add("is-visible"):e.classList.remove("is-visible")}const b=new w(".list a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
